name: ✨ Feature request
description: Suggest an idea or improvement for Connection Verify.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Thanks for helping improve Connection Verify!
  - type: checkboxes
    id: preflight
    attributes:
      label: Before you start
      options:
        - label: I searched the [existing issues](https://github.com/neramc/connection-verify/issues?q=is%3Aissue) and this has not been requested yet.
          required: true
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
      description: Is your request related to a problem? Please describe it.
      placeholder: "I'm always frustrated when ..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: Additional context
    validations:
      required: false
