package com.neramc.connectionverify;

import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * An immutable-ish snapshot of a single connection attempt (successful or failed).
 *
 * <p>A record is built up section by section while a login/join event is being
 * handled, assigned a 4-digit connection number by the {@link ConnectionRegistry},
 * and later rendered to a human-readable text report when an operator runs
 * {@code cnt <number>}.</p>
 */
public final class ConnectionRecord {

    /** Whether the connection succeeded or was denied. */
    public enum Status {
        SUCCESS,
        FAILED
    }

    private static final DateTimeFormatter TIMESTAMP =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss.SSS").withZone(ZoneOffset.UTC);

    private static final String FALLBACK = "(unknown)";
    private static final int BAR_WIDTH = 80;

    private final Status status;
    private final Instant recordedAt;
    private final List<Section> sections = new ArrayList<>();

    private String number = "----";

    public ConnectionRecord(Status status) {
        this.status = status;
        this.recordedAt = Instant.now();
    }

    /** Formats an instant as an UTC timestamp with its epoch-millisecond value. */
    public static String formatTimestamp(Instant instant) {
        return TIMESTAMP.format(instant) + " UTC (epoch ms: " + instant.toEpochMilli() + ")";
    }

    public Status status() {
        return status;
    }

    public Instant recordedAt() {
        return recordedAt;
    }

    public String number() {
        return number;
    }

    /** Package-private: only the registry assigns the connection number. */
    void setNumber(String number) {
        this.number = number;
    }

    /** Starts a new titled section and returns it so entries can be chained on. */
    public Section section(String title) {
        Section section = new Section(title);
        sections.add(section);
        return section;
    }

    /**
     * Renders this record as a plain-text report.
     *
     * @param savedAt the moment the report is being written to disk
     * @return the full report text
     */
    public String render(Instant savedAt) {
        String heavyBar = "=".repeat(BAR_WIDTH);
        String lightBar = "-".repeat(BAR_WIDTH);
        int keyWidth = computeKeyWidth();
        String newLine = System.lineSeparator();

        StringBuilder sb = new StringBuilder();
        sb.append(heavyBar).append(newLine);
        sb.append("  CONNECTION VERIFY  -  CONNECTION LOG").append(newLine);
        sb.append(heavyBar).append(newLine);
        appendEntry(sb, keyWidth, "Connection number", number);
        appendEntry(sb, keyWidth, "Status", status.name());
        appendEntry(sb, keyWidth, "Recorded at", formatTimestamp(recordedAt));
        appendEntry(sb, keyWidth, "Log saved at", formatTimestamp(savedAt));
        sb.append(lightBar).append(newLine);

        for (Section section : sections) {
            sb.append(newLine);
            sb.append("[ ").append(section.title).append(" ]").append(newLine);
            for (Map.Entry<String, String> entry : section.entries.entrySet()) {
                appendEntry(sb, keyWidth, entry.getKey(), entry.getValue());
            }
        }

        sb.append(newLine);
        sb.append(heavyBar).append(newLine);
        sb.append("  End of report - generated by Connection Verify").append(newLine);
        sb.append(heavyBar).append(newLine);
        return sb.toString();
    }

    private void appendEntry(StringBuilder sb, int keyWidth, String key, String value) {
        sb.append("  ")
          .append(padRight(key, keyWidth))
          .append(" : ")
          .append(value == null || value.isEmpty() ? FALLBACK : value)
          .append(System.lineSeparator());
    }

    private int computeKeyWidth() {
        int width = "Connection number".length();
        for (Section section : sections) {
            for (String key : section.entries.keySet()) {
                width = Math.max(width, key.length());
            }
        }
        return width;
    }

    private static String padRight(String value, int width) {
        if (value.length() >= width) {
            return value;
        }
        return value + " ".repeat(width - value.length());
    }

    /** A titled group of key/value entries inside a {@link ConnectionRecord}. */
    public static final class Section {

        private final String title;
        private final Map<String, String> entries = new LinkedHashMap<>();

        private Section(String title) {
            this.title = title;
        }

        /** Adds an entry from a direct value. {@code null} renders as {@code (unknown)}. */
        public Section add(String key, Object value) {
            entries.put(key, normalize(value == null ? null : String.valueOf(value)));
            return this;
        }

        /**
         * Adds an entry whose value is produced lazily and defensively.
         *
         * <p>If the supplier throws - for example an API method that is not
         * present in this particular server build, or a value that is invalid
         * in the current state - the failure is captured as
         * {@code (unavailable: <reason>)} instead of aborting the whole
         * snapshot. {@code null} still renders as {@code (unknown)}. This lets
         * a single record gather as much detail as possible without any one
         * field being able to break the capture.</p>
         */
        public Section add(String key, ValueSupplier supplier) {
            String value;
            try {
                Object result = supplier.get();
                value = result == null ? null : String.valueOf(result);
            } catch (Throwable throwable) {
                value = "(unavailable: " + throwable.getClass().getSimpleName() + ")";
            }
            entries.put(key, normalize(value));
            return this;
        }

        private static String normalize(String value) {
            return (value == null || value.isEmpty()) ? FALLBACK : value;
        }
    }

    /**
     * A value producer that is allowed to fail. Used by
     * {@link Section#add(String, ValueSupplier)} so each captured field is
     * isolated from the rest.
     */
    @FunctionalInterface
    public interface ValueSupplier {
        Object get() throws Exception;
    }
}
