/*
 * Copyright 2026 neramc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.neramc.connectionverify.format;

import com.neramc.connectionverify.connection.ConnectionRecord;
import com.neramc.connectionverify.connection.ConnectionRecord.Section;

import java.time.Instant;
import java.util.Map;

/** Renders a record as a human-readable, aligned plain-text report. */
public final class TextRecordFormatter implements RecordFormatter {

    private static final int BAR_WIDTH = 80;
    private static final String HEADER_KEY = "Connection number";

    @Override
    public String extension() {
        return "txt";
    }

    @Override
    public String format(ConnectionRecord record, Instant savedAt) {
        String heavyBar = "=".repeat(BAR_WIDTH);
        String lightBar = "-".repeat(BAR_WIDTH);
        int keyWidth = computeKeyWidth(record);
        String newLine = System.lineSeparator();

        StringBuilder sb = new StringBuilder(1024);
        sb.append(heavyBar).append(newLine);
        sb.append("  CONNECTION VERIFY  -  CONNECTION LOG").append(newLine);
        sb.append(heavyBar).append(newLine);
        appendEntry(sb, keyWidth, HEADER_KEY, record.number());
        appendEntry(sb, keyWidth, "Status", record.status().name());
        appendEntry(sb, keyWidth, "Recorded at", ConnectionRecord.formatTimestamp(record.recordedAt()));
        appendEntry(sb, keyWidth, "Log saved at", ConnectionRecord.formatTimestamp(savedAt));
        sb.append(lightBar).append(newLine);

        for (Section section : record.sections()) {
            sb.append(newLine);
            sb.append("[ ").append(section.title()).append(" ]").append(newLine);
            for (Map.Entry<String, String> entry : section.entries().entrySet()) {
                appendEntry(sb, keyWidth, entry.getKey(), entry.getValue());
            }
        }

        sb.append(newLine);
        sb.append(heavyBar).append(newLine);
        sb.append("  End of report - generated by Connection Verify").append(newLine);
        sb.append(heavyBar).append(newLine);
        return sb.toString();
    }

    private void appendEntry(StringBuilder sb, int keyWidth, String key, String value) {
        sb.append("  ")
          .append(padRight(key, keyWidth))
          .append(" : ")
          .append(value == null || value.isEmpty() ? ConnectionRecord.UNKNOWN : value)
          .append(System.lineSeparator());
    }

    private int computeKeyWidth(ConnectionRecord record) {
        int width = HEADER_KEY.length();
        for (Section section : record.sections()) {
            for (String key : section.entries().keySet()) {
                width = Math.max(width, key.length());
            }
        }
        return width;
    }

    private static String padRight(String value, int width) {
        if (value.length() >= width) {
            return value;
        }
        return value + " ".repeat(width - value.length());
    }
}
